apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: psycho007/portfolio
        resources:
          limits:
            cpu: '0.1'
            memory: 64Mi