apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: psycho007/caddy-custom
        volumeMounts:
          - mountPath: /srv
            name: proxy-site 
          - mountPath: /data
            name: proxy-data
          - mountPath: /config
            name: proxy-config
        resources:
          limits:
            cpu: '0.1'
            memory: 64Mi

      imagePullSecrets:
      - name: regcred
      volumes:
        - name: proxy-site 
          hostPath:
            path: /data/proxy-site
            type: DirectoryOrCreate
        - name: proxy-data 
          hostPath:
            path: /data/proxy-data/
            type: DirectoryOrCreate
        - name: proxy-config 
          hostPath:
            path: /data/proxy-config/ 
            type: DirectoryOrCreate